version: '3.7'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - clickhouse_net

  clickhouse1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse1
    ports:
      - "9001:9000"
      - "8124:8123"
    volumes:
      - clickhouse1_data:/var/lib/clickhouse
      - clickhouse1_config:/etc/clickhouse-server
    networks:
      - clickhouse_net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper

  clickhouse2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse2
    ports:
      - "9002:9000"
      - "8125:8123"
    volumes:
      - clickhouse2_data:/var/lib/clickhouse
      - clickhouse2_config:/etc/clickhouse-server
    networks:
      - clickhouse_net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper

  clickhouse3:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse3
    ports:
      - "9003:9000"
      - "8126:8123"
    volumes:
      - clickhouse3_data:/var/lib/clickhouse
      - clickhouse3_config:/etc/clickhouse-server
    networks:
      - clickhouse_net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper

volumes:
  clickhouse1_data:
  clickhouse1_config:
  clickhouse2_data:
  clickhouse2_config:
  clickhouse3_data:
  clickhouse3_config:

networks:
  clickhouse_net:
    driver: bridge

#apt-get update && apt-get install -y nano
